// <auto-generated />
using System;
using Emma.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emma.Service.Data.Migrations
{
    [DbContext(typeof(EmmaDbContext))]
    [Migration("20260824062711_MehrfeldParameter")]
    partial class MehrfeldParameter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Emma.Shared.Models.Aufgabe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AbgeschlossenAm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fehlermeldung")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProzessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProzessId");

                    b.ToTable("Aufgaben");
                });

            modelBuilder.Entity("Emma.Shared.Models.Prozess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterFelderJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prozesse");
                });

            modelBuilder.Entity("Emma.Shared.Models.WiederkehrenderPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LetzteAusfuehrung")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProzessId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Uhrzeit")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wochentag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProzessId");

                    b.ToTable("WiederkehrendePlaene");
                });

            modelBuilder.Entity("Emma.Shared.Models.Aufgabe", b =>
                {
                    b.HasOne("Emma.Shared.Models.Prozess", "Prozess")
                        .WithMany()
                        .HasForeignKey("ProzessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prozess");
                });

            modelBuilder.Entity("Emma.Shared.Models.WiederkehrenderPlan", b =>
                {
                    b.HasOne("Emma.Shared.Models.Prozess", "Prozess")
                        .WithMany()
                        .HasForeignKey("ProzessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prozess");
                });
#pragma warning restore 612, 618
        }
    }
}
